baseURL: https://mgetka.dev/
languageCode: en

title: mgetka.dev

markup:
  goldmark:
    parser:
      autoHeadingIDType: github-ascii
    renderer:
      unsafe: true
  highlight:
    style: pygments

timeZone: Europe/Warsaw

disableKinds:
  - taxonomy
  - term
